steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker:20.10.24'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/todo-mongo-demo:${SHORT_SHA}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/todo-mongo-demo']
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'todo-mongo-demo', '--image', 'gcr.io/$PROJECT_ID/todo-mongo-demo:${SHORT_SHA}', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
  env:
  - 'PORT=8080'
images:
- gcr.io/$PROJECT_ID/todo-mongo-demo
options:
  logging: CLOUD_LOGGING_ONLY
